name: Deploy To Beanstalk
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
strategy:
      matrix:
        node-version: [16.x]
steps:
    
    - uses: actions/checkout@v1
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Run npm install
      run: |
        npm install
    
    - name: Generate deployment package
      run: zip -r package.zip . -x ".git/*" -x ".github/*" -x ".vscode/*"
      
    - name: Get timestamp
      id: timestamp
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')"  
            
    - name: Run beanstalk deploy
      uses: einaregilsson/beanstalk-deploy@v2
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: aws_secret_access_key
        environment_name: node-app-ex-2022-1-dev
        region: us-east-1
        version_label: "${{ steps.timestamp.outputs.date }}"
        deployment_package: package.zip
